# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/santos10wifi/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/santos10wifi

PRODUCT_COPY_FILES += \
    vendor/samsung/santos10wifi/proprietary/vendor/bin/gpsd:$(TARGET_COPY_OUT_VENDOR)/bin/gpsd \
    vendor/samsung/santos10wifi/proprietary/vendor/lib/hw/camera.vendor.santos10.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.vendor.santos10.so \
    vendor/samsung/santos10wifi/proprietary/vendor/lib/hw/gps.santos10.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.santos10.so \
    vendor/samsung/santos10wifi/proprietary/vendor/lib/hw/hwcomposer.clovertrail.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.clovertrail.so
